### ISSUE TITLE
Process `POREC:pairsToCooler (1)` terminated with an error exit status (1)

### ISSUE THREAD

**Issue by malszycki** [epi2me-labs/wf-pore-c#9] opened 2023-05-19 10:06 UTC
### What happened?

Hi,
There seems to be some error with the cooler package in the workflow. Simillar error was posted in 2021 in cooler github, but I'm not sure it it's relevant : https://github.com/open2c/cooler/issues/248

I'm running the workflow on our institute's custom built HPC, and we need to use charliecloud instead of docker. Seems to work though and is probably not related to the error message.

Running script here:
```
# pull the charliecloud image
mkdir work/
ch-image pull -s work/charliecloud ontresearch/wf-pore-c:sha51e5a1f25db6981a781851783e93efd05f8ef266

# start the job 

nextflow \
  run \
    -without-docker \
    -with-charliecloud ontresearch/wf-pore-c:sha51e5a1f25db6981a781851783e93efd05f8ef266 \
    -profile local \
    -ansi-log \
    -offline \
  epi2me-labs/wf-pore-c \
    --sample_id $sample_id \
    --fastq $fastq \
    --ref $refgenome \
    --mcool \
    --mcool_resolutions 10,20,30 \
    --cutter NlaIII \
    --coverage \
    --pairs \
    --chromunity \
    --paired_end \
    --filter_pairs \
    --paired_end_minimum_distance 100 \
    --paired_end_maximum_distance 200 
```

### Operating System

ubuntu 20.04

### Workflow Execution

Command line

### Workflow Execution - CLI Execution Profile

None

### Workflow Version

wf-pore-c v0.0.5-gd613498

### Relevant log output

```shell
ERROR ~ Error executing process > 'POREC:pairsToCooler (1)'
  
Caused by:
  Process `POREC:pairsToCooler (1)` terminated with an error exit status (1)
  
Command executed:
  
  cooler cload pairs -c1 2 -p1 3 -c2 4 -p2 5 fasta.fai:1000 null.pairs.gz null.pairs.cool
  
Command exit status:
  1
  
Command output:
  (empty)
  
Command error:
  Traceback (most recent call last):
    File "/home/epi2melabs/conda/bin/cooler", line 10, in <module>
      sys.exit(cli())
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
      return self.main(*args, **kwargs)
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/click/core.py", line 1055, in main
      rv = self.invoke(ctx)
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
      return _process_result(sub_ctx.command.invoke(sub_ctx))
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
      return _process_result(sub_ctx.command.invoke(sub_ctx))
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/click/core.py", line 1404, in invoke              
      return ctx.invoke(self.callback, **ctx.params)
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/click/core.py", line 760, in invoke
      return __callback(*args, **kwargs)
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/cooler/cli/cload.py", line 551, in pairs
      f_in = get_handle(pairs_path, mode='r', compression='infer')[0]
  TypeError: 'IOHandles' object is not subscriptable
  
Work dir:
  /project/analysis/wf-pore-c/work/c1/2f2b3dc280afa56ffb1ba0334839ab
  
Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`
  
 -- Check '.nextflow.log' file for details
```

**Comment by sarahjeeeze** [comment] 2023-05-22 16:57
Hi, I have added a fix for this in v0.0.7

**Comment by sarahjeeeze** [comment] 2023-06-14 13:35
Hi, I think the problem was caused by the latest pandas version clashing with the cooler cload script. We pinned it for now. Did you get it to work in the end?

**Comment by sarahjeeeze** [comment] 2023-07-28 13:55
Closing through lack of response and this issue was resolved in a more recent version.

**Closed by sarahjeeeze** 2023-07-28 13:55 UTC
Labels: bug
